<div id="page">
<h2>tripseru.com</h2>
<p>tripseru.com berkomitmen untuk melindungi privasi Anda sesuai dengan standar tertinggi perlindungan konsumen. Kami hanya mengumpulkan informasi pribadi Anda untuk menyediakan layanan-layanan dan produk-produk yang lebih baik untuk Anda. Untuk memastikan Anda dapat membuat keputusan dan merasa yakin dalam memberikan informasi pribadi Anda sewaktu menggunakan website kami, kami menjaga prinsip-prinsip privasi sebagai berikut:</p>
<h2>Pengumpulan dan Penggunaan Informasi</h2>
<p>tripseru.com tidak akan mengumpulkan atau memantau informasi pribadi apapun tentang Anda tanpa persetujuan Anda. Informasi pribadi yang kami kumpulkan hanyalah yang Anda beritahukan pada kami dan informasi tentang bagaimana Anda menggunakan situs kami.</p>
<p>Jenis-jenis informasi yang kami kumpulkan, tergantung pada bagian-bagian tertentu layanan situs yang Anda gunakan,adalah sebagai berikut:</p>
<ul>
  <li>Nama</li>
  <li>Alamat email</li>
  <li>Nomor telepon</li>
  <li>Nomor fax</li>
  <li>Nomor HP</li>
  <li>Nama perusahaan</li>
</ul>
<p>Kami menggunakan informasi Anda untuk mengirimkan detail-detail tentang layanan kami atau rincian atas pesanan Anda. Namun, bila Anda memilih untuk tidak memberikan informasi seperti yang diminta, kami tidak dapat memberikan layanan online sepenuhnya kepada Anda. Kami juga akan menggunakan informasi Anda untuk memproses pembelian Anda atas produk atau jasa kami; untuk mengkonfirmasi perjalanan Anda; untuk memenuhi permintaan Anda saat Anda menggunakan layanan online kami; untuk menghubungi Anda mengenai pertanyaan Anda; dan untuk tujuan pemasaran kami, seperti mengirim keterangan mengenai penawaran khusus, promo, newsletter, brosur, dan lain-lain. Jika Anda tidak ingin kami menggunakan informasi Anda untuk mengirimkan rincian produk kami, silakan kirim email kepada kami.</p>
<p>Kami tidak akan membagikan rincian informasi pribadi Anda ke pihak ketiga kecuali seperti yang dijelaskan di bawah ini:</p>
<ul>
  <li>Kami dapat memberikan informasi Anda ke maskapai penerbangan, hotel, dan/atau agen travel yang bersangkutan. Namun, kami hanya akan memberikan informasi yang diperlukan untuk menjamin kelancaran perjalanan Anda.</li>
  <li>Selain pemberian informasi seperti yang disebutkan di atas, kami tidak memberikan informasi kontak Anda ke pihak lain tanpa persetujuan Anda, kecuali ada situasi darurat di mana informasi Anda diperlukan, atau atas perintah pengadilan, atau diminta oleh pemerintah atau penegak hukum, atau dalam itikad baik bahwa pengungkapan dinyatakan diperlukan atau dianjurkan untuk melindungi hak-hak. Hal ini juga berlaku bila kami memiliki alasan yang dapat dipercaya bahwa pengungkapan informasi diperlukan untuk mengidentifikasi, menghubungi, atau melaksanakan tindakan hukum terhadap seseorang yang mungkin bisa menyebabkan gangguan terhadap hak-hak atau properti kami, baik disengaja atau tidak, atau bila pihak lain dapat dirugikan oleh kegiatan tertentu.</li>
</ul>
<h2>Cookies</h2>
<p>Kunjungan Anda ke situs ini dapat direkam untuk analisis jumlah pengunjung tripseru.com dan pola penggunaan umum. Kami menggunakan &ldquo;cookies&rdquo; untuk mengumpulkan informasi tentang bagaimana situs kami digunakan. Informasi yang dikumpulkan dan dilacak adalah server komputer yang Anda gunakan, jenis browser (contohnya Internet Explorer atau Mozilla Firefox), dan apakah Anda sampai ke situs kami melalui iklan online atau Email. Informasi itu digunakan untuk mengukur tingkat respon tawaran yang kami ajukan melalui iklan dan Email. Cookies dapat membuat sebuah situs menjadi lebih bermanfaat dengan menyimpan informasi tentang preferensi Anda di situs-situs, sehingga memungkinkan pemilik website untuk memberikan fitur yang lebih berguna bagi pengguna mereka. Dengan menggunakan cookies, kami dapat melayani Anda dengan lebih baik ketika Anda kembali ke situs kami. Kebanyakan browser menerima cookies secara otomatis, tatapi Anda dapat mengedit opsi browser Anda untuk memblokirnya di masa depan. Namun, dengan menonaktifkannya, Anda mungkin tidak dapat mengambil manfaat sepenuhnya dari website kami.</p>
<h2>Keamanan</h2>
<p>tripseru.com telah lama berkomitmen untuk melindungi privasi konsumen dan kami juga aktif terlibat dalam inisiatif industri saat ini untuk menjaga hak-hak privasi individu di Internet. Kami menganggap masalah keamanan sebagai masalah yang serius dan memperlakukan semua informasi pribadi yang diperoleh dari pengguna situs kami secara rahasia, serta mencegah akses yang tidak sah dan memastikan informasi digunakan secara tepat. Selain firewall dan teknologi lainnya yang diterapkan, kami juga menyediakan langkah-langkah manajerial, fisik, dan elektronik untuk melindungi sistem kami, dan informasi dan data yang terkandung di dalamnya dari gangguan atau kerusakan yang disengaja atau tidak. Ketika Anda memasukkan informasi yang sensitif, informasi itu akan secara otomatis dikonversi ke dalam kode-kode sebelum dikirimkan melalui Internet secara aman. Namun, kerahasiaan dan keamanan yang sempurna di Internet belum memungkinkan, dan privasi tidak dapat terjamin dalam komunikasi Anda kepada kami. Anda mengakui bahwa informasi pribadi yang diungkapkan adalah risiko Anda sendiri dan ada kemungkinan terjadinya penggunaan yang tidak sah oleh pihak lain. Bila ini terjadi, Anda mungkin akan menerima pesan/email dari pihak-pihak di luar tripseru.com. Kami tidak bertanggung jawab untuk kerusakan yang terjadi secara langsung, tidak langsung atau konsekuensial, yang disebabkan oleh komunikasi informasi kepada kami.</p>
<h2>Links</h2>
<p>Situs ini mungkin berisi link ke situs lain yang memiliki ketentuan privasi mereka sendiri. Perlu diketahui bahwa kami tidak bertanggung jawab atas kebijakan privasi mereka atau kesesuaian dengan hukum, dan tidak menjamin keamanan dari situs-situs lain tersebut. Oleh karena itu Anda harus sepenuhnya menyadari bahwa adanya link tersebut tidak mengandung suatu dukungan, persetujuan, atau bentuk asosiasi oleh atau dengan perusahaan kami. Karena itu Anda harus tetap waspada ketika meninggalkan situs kami, dan membaca pernyataan privasi dari situs-situs lain. Kami tidak memiliki kendali atas data yang disampaikan oleh pihak ketiga tersebut. Anda mengakses data di situs tersebut atas risiko Anda sendiri dan kami sarankan Anda membaca pernyataan privasi ketika memasuki situs tersebut.</p>
<h2>Perubahan Ketentuan Privasi Kami</h2>
<p>Kami akan post pernyataan baru kami pada halaman ini bila kami mengubah kebijakan privasi kami, sehingga Anda selalu tahu tentang cara kami mengumpulkan dan menggunakan informasi. Jika suatu saat kami memutuskan untuk menggunakan informasi yang Anda sampaikan pada saat pernyataan yang telah direvisi berlaku, Anda akan diberikan kesempatan melalui email, website atau secara tertulis untuk memilih untuk melepas keikutsertaan Anda atau mencegah penggunaan tersebut. Jika Anda memiliki pertanyaan atau keluhan mengenai Pernyataan Privasi kami, atau jika sewaktu-waktu Anda membutuhkan bantuan terkait dengan layanan kami, silahkan hubungi:</p>
<h4>tripseru.com : privacy@tripseru.com</h4>
</div>
</body>
</html>